
# Self-service password reset from the authentication page.
#
# Two modes, driven by options("shinymanager.reset_password"):
#  - TRUE        : the user must provide a username AND the email associated with
#                  it (the email is verified against the credentials table).
#  - "username"  : the user only provides a username; the temporary password is
#                  sent to whatever email is stored for that user (if any).
#
# In both cases a temporary password is generated and sent using the 'send_mail'
# callback configured in secure_server(). The new password is persisted only if
# the email has been sent successfully, so a failing mail server never locks the
# user out. The user is then forced to change the password on next login
# (must_change).
#
# With options("shinymanager.reset_password_validity" = X), the temporary
# password is only usable for X minutes (see set_temp_pwd_expire /
# is_temp_pwd_expired). This only concerns passwords sent by this self-service
# reset: passwords generated by an admin (user creation, admin reset) never
# expire this way, and an admin reset cancels a pending mailed one.
#
# Only available with a SQLite or SQL backend (the data.frame backend is not
# persistent). Returns a list with two slots:
#  - result : logical, TRUE if the password was reset.
#  - reason : a short server-side code describing the outcome, used ONLY for
#             admin-side logging (see save_reset_logs). It must never be shown to
#             the visitor: the caller always displays the same generic message to
#             avoid account enumeration.

# Decide, from the stored email, why a reset is (not) allowed.
# Returns "ok", "no_stored_email" or "email_mismatch".
email_reset_reason <- function(stored_email, email, require_email) {
  stored_email <- trimws(as.character(stored_email))
  if (length(stored_email) != 1 || is.na(stored_email) || !nzchar(stored_email)) {
    return("no_stored_email")
  }
  if (require_email && !identical(tolower(stored_email), tolower(email))) {
    return("email_mismatch")
  }
  "ok"
}

# Log a reset attempt to the admin logs, mapping the internal reason to a status.
# Only outcomes based on the submitted username / email are logged; technical
# cases (config, empty input, mail failure, db error) are skipped.
save_reset_logs <- function(user, reason) {
  if (!write_logs_enabled()) {
    return(invisible())
  }
  status <- switch(
    reason,
    "success"         = "Reset password",
    "unknown_user"    = "Reset password: unknown user",
    "email_mismatch"  = "Reset password: wrong email",
    "no_stored_email" = "Reset password: no email",
    NULL
  )
  if (!is.null(status)) {
    save_logs_failed(user, status = status)
  }
  invisible()
}

# Expiration of the temporary password sent by mail
# --------------------------------------------------
# Stored in the 'temp_pwd_expire' column of the pwd_mngt table, as text
# "YYYY-MM-DD HH:MM:SS" in UTC, consistent with the other dates of shinymanager
# stored as text (date_change in SQLite, server_connected in logs). An empty
# value means "no expiration".
#
# SQLite: the column is created on the fly the first time an expiration is set.
# SQL: the column is NOT created by shinymanager; add it to your pwd_mngt table
# as a text column (e.g. varchar(19), or STRING with BigQuery / Spark) to use the
# feature. Without it nothing is stored and the temporary password never expires.
# No timestamp conversion is done on write (in particular not in the Spark
# 'col_date' conversion of write_sql_db, which casts to Date and would drop the
# time), so a text column is the supported type.

# Expiration to store for a freshly mailed temporary password, "" if no
# validity is configured.
temp_pwd_expire_value <- function() {
  validity <- get_reset_password_validity()
  if (is.na(validity)) {
    return("")
  }
  format(Sys.time() + validity * 60, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
}

# Set (expire = "YYYY-MM-DD HH:MM:SS") or clear (expire = "") the temporary
# password expiration of a user. Clearing never creates the column.
#' @importFrom DBI dbConnect dbDisconnect dbGetQuery dbExecute SQL
#' @importFrom RSQLite SQLite
#' @importFrom glue glue_sql
set_temp_pwd_expire <- function(user, expire = "") {
  sqlite_path <- .tok$get_sqlite_path()
  passphrase  <- .tok$get_passphrase()
  config_db   <- .tok$get_sql_config_db()

  # sqlite
  if (!is.null(sqlite_path)) {
    conn <- dbConnect(SQLite(), dbname = sqlite_path)
    on.exit(dbDisconnect(conn))
    resetpwd <- read_db_decrypt(conn, name = "pwd_mngt", passphrase = passphrase)
    if (!"temp_pwd_expire" %in% colnames(resetpwd)) {
      if (!nzchar(expire)) {
        return(invisible(FALSE))
      }
      resetpwd$temp_pwd_expire <- rep("", nrow(resetpwd))
    }
    resetpwd$temp_pwd_expire[resetpwd$user %in% user] <- expire
    write_db_encrypt(conn, value = resetpwd, name = "pwd_mngt", passphrase = passphrase)
    return(invisible(TRUE))

  } else if (!is.null(config_db)) {
    conn <- connect_sql_db(config_db)
    on.exit(disconnect_sql_db(conn, config_db))

    tablename <- SQL(config_db$tables$pwd_mngt$tablename)
    request <- glue_sql(config_db$tables$pwd_mngt$select, .con = conn)
    resetpwd <- dbGetQuery(conn, request)
    # optional column, not created by shinymanager on SQL backends
    if (!"temp_pwd_expire" %in% colnames(resetpwd)) {
      return(invisible(FALSE))
    }

    udpate_users <- user
    name <- "temp_pwd_expire"
    value <- expire
    request <- glue_sql(config_db$tables$pwd_mngt$update, .con = conn)
    dbExecute(conn, request)
    return(invisible(TRUE))
  }
  invisible(FALSE)
}

# TRUE if the user holds a mailed temporary password whose validity has passed.
# Missing column, empty or unreadable value: no expiration (FALSE), which is the
# case of every password generated by an admin.
#' @importFrom DBI dbConnect dbDisconnect dbGetQuery SQL
#' @importFrom RSQLite SQLite
#' @importFrom glue glue_sql
is_temp_pwd_expired <- function(user) {
  sqlite_path <- .tok$get_sqlite_path()
  passphrase  <- .tok$get_passphrase()
  config_db   <- .tok$get_sql_config_db()

  if (!is.null(sqlite_path)) {
    conn <- dbConnect(SQLite(), dbname = sqlite_path)
    on.exit(dbDisconnect(conn))
    resetpwd <- read_db_decrypt(conn, name = "pwd_mngt", passphrase = passphrase)
    resetpwd <- resetpwd[resetpwd$user %in% user, , drop = FALSE]
  } else if (!is.null(config_db)) {
    conn <- connect_sql_db(config_db)
    on.exit(disconnect_sql_db(conn, config_db))
    tablename <- SQL(config_db$tables$pwd_mngt$tablename)
    request <- glue_sql(config_db$tables$pwd_mngt$select, .con = conn)
    resetpwd <- dbGetQuery(conn, request)
  } else {
    return(FALSE)
  }

  if (!"temp_pwd_expire" %in% colnames(resetpwd) || nrow(resetpwd) == 0) {
    return(FALSE)
  }
  expire <- resetpwd$temp_pwd_expire[1]
  # text (expected) or a timestamp if the SQL column was typed so
  if (!inherits(expire, "POSIXct")) {
    expire <- tryCatch(as.POSIXct(as.character(expire), tz = "UTC"), error = function(e) NA)
  }
  isTRUE(Sys.time() > expire)
}

#' @importFrom DBI dbConnect dbDisconnect dbGetQuery dbExecute SQL
#' @importFrom RSQLite SQLite
#' @importFrom glue glue_sql
#' @importFrom scrypt hashPassword
reset_pwd_user_email <- function(user, email = NULL) {
  send_mail <- .tok$get_send_mail()
  if (!is.function(send_mail)) {
    return(list(result = FALSE, reason = "no_mailer"))
  }
  if (is.null(user) || !nzchar(trimws(user))) {
    return(list(result = FALSE, reason = "empty_input"))
  }

  require_email <- !reset_password_username_only()
  if (require_email && (is.null(email) || !nzchar(trimws(email)))) {
    return(list(result = FALSE, reason = "empty_input"))
  }

  user <- trimws(user)
  email <- if (is.null(email)) "" else trimws(email)

  email_col <- get_email_column()

  sqlite_path <- .tok$get_sqlite_path()
  passphrase  <- .tok$get_passphrase()
  config_db   <- .tok$get_sql_config_db()

  # sqlite
  if (!is.null(sqlite_path)) {
    conn <- dbConnect(SQLite(), dbname = sqlite_path)
    on.exit(dbDisconnect(conn))

    users <- read_db_decrypt(conn, name = "credentials", passphrase = passphrase)
    if (!email_col %in% colnames(users)) {
      return(list(result = FALSE, reason = "no_email_column"))
    }
    ind_user <- which(users$user == user)
    if (length(ind_user) != 1) {
      return(list(result = FALSE, reason = "unknown_user"))
    }
    stored_email <- as.character(users[[email_col]][ind_user])
    reason <- email_reset_reason(stored_email, email, require_email)
    if (reason != "ok") {
      return(list(result = FALSE, reason = reason))
    }

    temp_pwd <- generate_pwd()

    # send email first: only persist the new password if the mail is sent
    sent <- tryCatch({
      send_mail(user, stored_email, temp_pwd)
      TRUE
    }, error = function(e) FALSE)
    if (!isTRUE(sent)) {
      return(list(result = FALSE, reason = "mail_failed"))
    }

    res_pwd <- try({
      if (!"character" %in% class(users$password)) {
        users$password <- as.character(users$password)
      }
      users$password[ind_user] <- temp_pwd
      if (!"is_hashed_password" %in% colnames(users)) {
        users$is_hashed_password <- FALSE
      }
      users$is_hashed_password[ind_user] <- FALSE
      write_db_encrypt(conn, value = users, name = "credentials", passphrase = passphrase)
      force_chg_pwd(user, TRUE)
      # limited validity of the mailed password (also replaces a previous one)
      set_temp_pwd_expire(user, temp_pwd_expire_value())
    }, silent = TRUE)
    ok <- !inherits(res_pwd, "try-error")
    return(list(result = ok, reason = if (ok) "success" else "db_error"))

  } else if (!is.null(config_db)) {
    conn <- connect_sql_db(config_db)
    on.exit(disconnect_sql_db(conn, config_db))

    tablename <- SQL(config_db$tables$credentials$tablename)
    request <- glue_sql(config_db$tables$credentials$select, .con = conn)
    user_info <- dbGetQuery(conn, request)
    if (nrow(user_info) != 1) {
      return(list(result = FALSE, reason = "unknown_user"))
    }
    if (!email_col %in% colnames(user_info)) {
      return(list(result = FALSE, reason = "no_email_column"))
    }
    stored_email <- as.character(user_info[[email_col]][1])
    reason <- email_reset_reason(stored_email, email, require_email)
    if (reason != "ok") {
      return(list(result = FALSE, reason = reason))
    }

    temp_pwd <- generate_pwd()

    sent <- tryCatch({
      send_mail(user, stored_email, temp_pwd)
      TRUE
    }, error = function(e) FALSE)
    if (!isTRUE(sent)) {
      return(list(result = FALSE, reason = "mail_failed"))
    }

    res_pwd <- try({
      value <- scrypt::hashPassword(temp_pwd)
      name <- "password"
      udpate_users <- user

      tablename <- SQL(config_db$tables$credentials$tablename)
      request <- glue_sql(config_db$tables$credentials$update, .con = conn)
      dbExecute(conn, request)

      force_chg_pwd(user, TRUE)
      # limited validity of the mailed password (also replaces a previous one)
      set_temp_pwd_expire(user, temp_pwd_expire_value())
    }, silent = TRUE)
    ok <- !inherits(res_pwd, "try-error")
    return(list(result = ok, reason = if (ok) "success" else "db_error"))

  } else {
    return(list(result = FALSE, reason = "backend"))
  }
}
