
# Self-service password reset from the authentication page.
#
# Two modes, driven by options("shinymanager.reset_password"):
#  - TRUE        : the user must provide a username AND the email associated with
#                  it (the email is verified against the credentials table).
#  - "username"  : the user only provides a username; the temporary password is
#                  sent to whatever email is stored for that user (if any).
#
# In both cases a temporary password is generated and sent using the 'send_mail'
# callback configured in secure_server(). The new password is persisted only if
# the email has been sent successfully, so a failing mail server never locks the
# user out. The user is then forced to change the password on next login
# (must_change).
#
# With options("shinymanager.reset_password_validity" = X), the temporary
# password is only usable for X minutes (see set_temp_pwd_expire /
# is_temp_pwd_expired). This only concerns passwords sent by this self-service
# reset: passwords generated by an admin (user creation, admin reset) never
# expire this way, and an admin reset cancels a pending mailed one.
#
# With options("shinymanager.reset_password_max" = N), a user can only request N
# resets in a row: the 'n_user_reset' counter of pwd_mngt is reset to 0 on the
# next successful login with a non temporary password, or by an admin reset.
# With options("shinymanager.reset_password_unlock" = FALSE), an account locked
# by too many wrong passwords can only be unlocked by an admin.
#
# Only available with a SQLite or SQL backend (the data.frame backend is not
# persistent). Returns a list with two slots:
#  - result : logical, TRUE if the password was reset.
#  - reason : a short server-side code describing the outcome, used for
#             admin-side logging (see save_reset_logs). The visitor only sees a
#             generic message, except for the reasons of reset_reason_blocked()
#             and reset_reason_error() (see module-auth.R).

# Decide, from the stored email, why a reset is (not) allowed.
# Returns "ok", "no_stored_email" or "email_mismatch".
email_reset_reason <- function(stored_email, email, require_email) {
  stored_email <- trimws(as.character(stored_email))
  if (length(stored_email) != 1 || is.na(stored_email) || !nzchar(stored_email)) {
    return("no_stored_email")
  }
  if (require_email && !identical(tolower(stored_email), tolower(email))) {
    return("email_mismatch")
  }
  "ok"
}

# Account-level checks, once the user and email are validated.
# Returns "ok", "account_expired", "unauthorized", "locked_account" or
# "too_many_resets". 'user_info' is the credentials row of the user.
account_reset_reason <- function(user, user_info) {
  to_date <- function(x) {
    tryCatch(as.Date(as.character(x)), error = function(e) as.Date(NA))
  }
  # same rules as check_credentials(): no reset for an account that can't log in
  if (isTRUE(to_date(user_info[["start"]]) > Sys.Date()) || isTRUE(to_date(user_info[["expire"]]) < Sys.Date())) {
    return("account_expired")
  }
  if (hasName(user_info, "applications")) {
    appsnames <- unlist(strsplit(as.character(user_info[["applications"]]), split = ";"), use.names = FALSE)
    if (!isTRUE(get_appname() %in% appsnames)) {
      return("unauthorized")
    }
  }
  if (!reset_password_unlock_enabled()) {
    pwd_failure_limit <- as.numeric(get_pwd_failure_limit())
    if (is_finite_limit(pwd_failure_limit) && isTRUE(check_locked_account(user, pwd_failure_limit))) {
      return("locked_account")
    }
  }
  if (get_n_user_reset(user) >= get_reset_password_max()) {
    return("too_many_resets")
  }
  "ok"
}

# Reasons shown to the visitor with a dedicated message: the account exists but
# can't reset its password, an administrator is needed.
reset_reason_blocked <- function() {
  c("locked_account", "too_many_resets")
}

# Reasons shown to the visitor as an error popup: the email could not be sent
# (or the new password not saved), or the reset is misconfigured.
reset_reason_error <- function() {
  c("mail_failed", "db_error", "no_mailer", "no_email_column", "backend")
}

# Minimal time (seconds) before the reset button is enabled again, whatever the
# outcome (see module-auth.R)
reset_btn_delay <- 5

# Log a reset attempt to the admin logs, mapping the internal reason to a status.
# Only an empty input is not logged.
save_reset_logs <- function(user, reason) {
  if (!write_logs_enabled()) {
    return(invisible())
  }
  status <- switch(
    reason,
    "success"         = "Reset password",
    "unknown_user"    = "Reset password: unknown user",
    "email_mismatch"  = "Reset password: wrong email",
    "no_stored_email" = "Reset password: no email",
    "account_expired" = "Reset password: account expired",
    "unauthorized"    = "Reset password: unauthorized",
    "locked_account"  = "Reset password: locked account",
    "too_many_resets" = "Reset password: too many resets",
    "too_soon"        = "Reset password: too soon",
    "mail_failed"     = "Reset password: mail failed",
    "db_error"        = "Reset password: db error",
    "no_mailer"       = "Reset password: config error",
    "no_email_column" = "Reset password: config error",
    "backend"         = "Reset password: config error",
    NULL
  )
  if (!is.null(status)) {
    save_logs_failed(user, status = status)
  }
  invisible()
}

# Expiration of the temporary password sent by mail
# --------------------------------------------------
# Stored in the 'temp_pwd_expire' column of the pwd_mngt table, as text
# "YYYY-MM-DD HH:MM:SS" in UTC, consistent with the other dates of shinymanager
# stored as text (date_change in SQLite, server_connected in logs). An empty
# value means "no expiration".
#
# SQLite: the column is created on the fly the first time an expiration is set.
# SQL: the column is NOT created by shinymanager; add it to your pwd_mngt table
# as a text column (e.g. varchar(19), or STRING with BigQuery / Spark) to use the
# feature. Without it nothing is stored and the temporary password never expires.
# No timestamp conversion is done on write (in particular not in the Spark
# 'col_date' conversion of write_sql_db, which casts to Date and would drop the
# time), so a text column is the supported type.

# Expiration to store for a freshly mailed temporary password, "" if no
# validity is configured.
temp_pwd_expire_value <- function() {
  validity <- get_reset_password_validity()
  if (is.na(validity)) {
    return("")
  }
  format(Sys.time() + validity * 60, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
}

# Set (expire = "YYYY-MM-DD HH:MM:SS") or clear (expire = "") the temporary
# password expiration of a user. Clearing never creates the column.
set_temp_pwd_expire <- function(user, expire = "") {
  set_pwd_mngt_optional(user, name = "temp_pwd_expire", value = expire, empty = "")
}

# Set the value of an optional column of pwd_mngt ('temp_pwd_expire',
# 'n_user_reset') for a user. SQLite: the column is created on the fly (filled
# with 'empty'), unless 'value' is 'empty' itself. SQL: the column is never
# created, nothing is done if it is missing. Returns TRUE if a value was written.
#' @importFrom DBI dbConnect dbDisconnect dbGetQuery dbExecute SQL
#' @importFrom RSQLite SQLite
#' @importFrom glue glue_sql
set_pwd_mngt_optional <- function(user, name, value, empty) {
  sqlite_path <- .tok$get_sqlite_path()
  passphrase  <- .tok$get_passphrase()
  config_db   <- .tok$get_sql_config_db()

  # sqlite
  if (!is.null(sqlite_path)) {
    conn <- dbConnect(SQLite(), dbname = sqlite_path)
    on.exit(dbDisconnect(conn))
    resetpwd <- read_db_decrypt(conn, name = "pwd_mngt", passphrase = passphrase)
    if (!name %in% colnames(resetpwd)) {
      if (identical(value, empty)) {
        return(invisible(FALSE))
      }
      resetpwd[[name]] <- rep(empty, nrow(resetpwd))
    }
    resetpwd[[name]][resetpwd$user %in% user] <- value
    write_db_encrypt(conn, value = resetpwd, name = "pwd_mngt", passphrase = passphrase)
    return(invisible(TRUE))

  } else if (!is.null(config_db)) {
    conn <- connect_sql_db(config_db)
    on.exit(disconnect_sql_db(conn, config_db))

    tablename <- SQL(config_db$tables$pwd_mngt$tablename)
    request <- glue_sql(config_db$tables$pwd_mngt$select, .con = conn)
    resetpwd <- dbGetQuery(conn, request)
    # optional column, not created by shinymanager on SQL backends
    if (!name %in% colnames(resetpwd)) {
      return(invisible(FALSE))
    }

    udpate_users <- user
    request <- glue_sql(config_db$tables$pwd_mngt$update, .con = conn)
    dbExecute(conn, request)
    return(invisible(TRUE))
  }
  invisible(FALSE)
}

# Row(s) of the pwd_mngt table for a user (0 row if unknown or no backend).
#' @importFrom DBI dbConnect dbDisconnect dbGetQuery SQL
#' @importFrom RSQLite SQLite
#' @importFrom glue glue_sql
read_pwd_mngt_user <- function(user) {
  sqlite_path <- .tok$get_sqlite_path()
  passphrase  <- .tok$get_passphrase()
  config_db   <- .tok$get_sql_config_db()

  if (!is.null(sqlite_path)) {
    conn <- dbConnect(SQLite(), dbname = sqlite_path)
    on.exit(dbDisconnect(conn))
    resetpwd <- read_db_decrypt(conn, name = "pwd_mngt", passphrase = passphrase)
    resetpwd[resetpwd$user %in% user, , drop = FALSE]
  } else if (!is.null(config_db)) {
    conn <- connect_sql_db(config_db)
    on.exit(disconnect_sql_db(conn, config_db))
    tablename <- SQL(config_db$tables$pwd_mngt$tablename)
    request <- glue_sql(config_db$tables$pwd_mngt$select, .con = conn)
    dbGetQuery(conn, request)
  } else {
    data.frame()
  }
}

# Stops if the pwd_mngt row of a user can't store a temporary password: no row
# (the password would not be temporary), or a 'temp_pwd_expire' column which is
# not text (e.g. a timestamp column on a SQL backend, see above).
check_reset_pwd_mngt <- function(resetpwd) {
  if (nrow(resetpwd) != 1) {
    stop("user not found in pwd_mngt", call. = FALSE)
  }
  if ("temp_pwd_expire" %in% colnames(resetpwd) && inherits(resetpwd$temp_pwd_expire, c("POSIXt", "Date"))) {
    stop("the 'temp_pwd_expire' column of pwd_mngt must be a text column", call. = FALSE)
  }
  invisible(TRUE)
}

# TRUE if the user holds a mailed temporary password whose validity has passed.
# Missing column, empty or unreadable value: no expiration (FALSE), which is the
# case of every password generated by an admin.
is_temp_pwd_expired <- function(user) {
  resetpwd <- read_pwd_mngt_user(user)

  if (!"temp_pwd_expire" %in% colnames(resetpwd) || nrow(resetpwd) == 0) {
    return(FALSE)
  }
  expire <- resetpwd$temp_pwd_expire[1]
  # text (expected) or a timestamp if the SQL column was typed so
  if (!inherits(expire, "POSIXct")) {
    expire <- tryCatch(as.POSIXct(as.character(expire), tz = "UTC"), error = function(e) NA)
  }
  isTRUE(Sys.time() > expire)
}

# Number of resets in a row
# -------------------------
# Stored in the optional 'n_user_reset' column of pwd_mngt, only used when
# options("shinymanager.reset_password_max") is set. Same rules as
# 'temp_pwd_expire': created on the fly with SQLite, to add manually (integer)
# with SQL, no limit if missing.

# Current number of resets of a user, 0 if no limit, unknown or missing column.
get_n_user_reset <- function(user) {
  if (is.infinite(get_reset_password_max())) {
    return(0)
  }
  resetpwd <- read_pwd_mngt_user(user)
  if (!"n_user_reset" %in% colnames(resetpwd) || nrow(resetpwd) == 0) {
    return(0)
  }
  n <- suppressWarnings(as.numeric(resetpwd$n_user_reset[1]))
  if (is.na(n)) 0 else n
}

#' @importFrom DBI dbConnect dbDisconnect dbGetQuery dbExecute SQL
#' @importFrom RSQLite SQLite
#' @importFrom glue glue_sql
#' @importFrom scrypt hashPassword
reset_pwd_user_email <- function(user, email = NULL) {
  send_mail <- .tok$get_send_mail()
  if (!is.function(send_mail)) {
    warning("shinymanager: password reset enabled but no 'send_mail' function given to secure_server()", call. = FALSE)
    return(list(result = FALSE, reason = "no_mailer"))
  }
  if (is.null(user) || !nzchar(trimws(user))) {
    return(list(result = FALSE, reason = "empty_input"))
  }

  require_email <- !reset_password_username_only()
  if (require_email && (is.null(email) || !nzchar(trimws(email)))) {
    return(list(result = FALSE, reason = "empty_input"))
  }

  user <- trimws(user)
  email <- if (is.null(email)) "" else trimws(email)

  email_col <- get_email_column()

  sqlite_path <- .tok$get_sqlite_path()
  passphrase  <- .tok$get_passphrase()
  config_db   <- .tok$get_sql_config_db()

  # read the credentials row of the user, and how to save the new password
  if (!is.null(sqlite_path)) {
    conn <- dbConnect(SQLite(), dbname = sqlite_path)
    on.exit(dbDisconnect(conn))
    users <- read_db_decrypt(conn, name = "credentials", passphrase = passphrase)
    user_info <- users[users$user %in% user, , drop = FALSE]
    save_reset_pwd <- function(temp_pwd) save_reset_pwd_sqlite(conn, user, temp_pwd, passphrase, user_info, email_col)
  } else if (!is.null(config_db)) {
    conn <- connect_sql_db(config_db)
    on.exit(disconnect_sql_db(conn, config_db))
    tablename <- SQL(config_db$tables$credentials$tablename)
    request <- glue_sql(config_db$tables$credentials$select, .con = conn)
    user_info <- dbGetQuery(conn, request)
    save_reset_pwd <- function(temp_pwd) save_reset_pwd_sql(conn, config_db, user, temp_pwd, user_info, email_col)
  } else {
    warning("shinymanager: password reset needs a SQLite or SQL database", call. = FALSE)
    return(list(result = FALSE, reason = "backend"))
  }

  # checked before the user, so the answer is the same for known / unknown users
  if (!email_col %in% colnames(user_info)) {
    warning(paste0("shinymanager: password reset needs a '", email_col, "' column in the credentials"), call. = FALSE)
    return(list(result = FALSE, reason = "no_email_column"))
  }
  if (nrow(user_info) != 1) {
    return(list(result = FALSE, reason = "unknown_user"))
  }
  stored_email <- as.character(user_info[[email_col]][1])
  reason <- email_reset_reason(stored_email, email, require_email)
  if (reason != "ok") {
    return(list(result = FALSE, reason = reason))
  }
  reason <- account_reset_reason(user, user_info)
  if (reason != "ok") {
    return(list(result = FALSE, reason = reason))
  }
  # checked before sending the email, as the password could not be saved
  pwd_mngt_ok <- tryCatch({
    check_reset_pwd_mngt(read_pwd_mngt_user(user))
    TRUE
  }, error = function(e) {
    warning(paste("shinymanager: unable to reset the password | error:", conditionMessage(e)), call. = FALSE)
    FALSE
  })
  if (!pwd_mngt_ok) {
    return(list(result = FALSE, reason = "db_error"))
  }

  temp_pwd <- generate_pwd()

  # send email first: only persist the new password if the mail is sent
  sent <- tryCatch({
    send_mail(user, trimws(stored_email), temp_pwd)
    TRUE
  }, error = function(e) {
    warning(paste(
      "shinymanager: unable to send the reset password email | error:", conditionMessage(e)
    ), call. = FALSE)
    FALSE
  })
  if (!isTRUE(sent)) {
    return(list(result = FALSE, reason = "mail_failed"))
  }

  res_pwd <- try(save_reset_pwd(temp_pwd), silent = TRUE)
  ok <- !inherits(res_pwd, "try-error")
  if (!ok) {
    warning(paste(
      "shinymanager: unable to save the reset password | error:", attr(res_pwd, "condition")$message
    ), call. = FALSE)
  }
  list(result = ok, reason = if (ok) "success" else "db_error")
}


# Saving the mailed temporary password
# ------------------------------------
# Everything is written on the same connection, in a single transaction: the
# password (credentials) and, in pwd_mngt, what force_chg_pwd(user, TRUE),
# set_temp_pwd_expire() and the reset counter would write. So a failure leaves
# the old password and state untouched (no temporary password without
# must_change or expiration).

# Run fun() in a transaction (rollback on error), directly for the backends
# without transactions (BigQuery, Spark). For the other backends, an error of
# dbBegin() stops here: nothing is written outside a transaction.
#' @importFrom DBI dbBegin dbCommit dbRollback
run_in_transaction <- function(conn, fun) {
  started <- !inherits(conn, c("BigQueryConnection", "spark_connection"))
  if (started) {
    dbBegin(conn)
  }
  res <- tryCatch(fun(), error = function(e) {
    if (started) try(dbRollback(conn), silent = TRUE)
    stop(e)
  })
  if (started) dbCommit(conn)
  res
}

# The password and email must not have been modified (by an admin, another
# session) while sending the email: the mailed password would overwrite the new
# one, or would have been sent to the old address. 'user_info' is the
# credentials row read before sending (no check if NULL).
check_reset_unchanged <- function(current, user_info, email_col) {
  if (is.null(user_info)) {
    return(invisible(TRUE))
  }
  same <- function(col) {
    identical(as.character(current[[col]][1]), as.character(user_info[[col]][1]))
  }
  if (!same("password") || !same(email_col)) {
    stop("account modified while sending the email", call. = FALSE)
  }
  invisible(TRUE)
}

# SQLite: both tables are re-read inside the transaction, as they may have been
# modified (by an admin, another session) while sending the email.
save_reset_pwd_sqlite <- function(conn, user, temp_pwd, passphrase, user_info = NULL, email_col = NULL) {
  # hashed before the transaction, to keep it short
  hashed_pwd <- scrypt::hashPassword(temp_pwd)
  expire <- temp_pwd_expire_value()
  run_in_transaction(conn, function() {
    users <- read_db_decrypt(conn, name = "credentials", passphrase = passphrase)
    ind_user <- which(users$user == user)
    if (length(ind_user) != 1) {
      stop("user not found in credentials", call. = FALSE)
    }
    check_reset_unchanged(users[ind_user, , drop = FALSE], user_info, email_col)
    if (!"character" %in% class(users$password)) {
      users$password <- as.character(users$password)
    }
    if (!"is_hashed_password" %in% colnames(users)) {
      users$is_hashed_password <- FALSE
    }
    users$password[ind_user] <- hashed_pwd
    users$is_hashed_password[ind_user] <- TRUE

    resetpwd <- read_db_decrypt(conn, name = "pwd_mngt", passphrase = passphrase)
    ind_pwd <- resetpwd$user %in% user
    # without its pwd_mngt row, the temporary password would not be temporary
    if (sum(ind_pwd) != 1) {
      stop("user not found in pwd_mngt", call. = FALSE)
    }
    # force_chg_pwd(user, TRUE): must change, unlocked
    if (nrow(resetpwd) > 0 && !"n_wrong_pwd" %in% colnames(resetpwd)) {
      resetpwd$n_wrong_pwd <- 0
    }
    resetpwd$must_change[ind_pwd] <- TRUE
    resetpwd$n_wrong_pwd[ind_pwd] <- 0
    # set_temp_pwd_expire(): the column is only created to store a value
    if (nzchar(expire) && !"temp_pwd_expire" %in% colnames(resetpwd)) {
      resetpwd$temp_pwd_expire <- rep("", nrow(resetpwd))
    }
    if ("temp_pwd_expire" %in% colnames(resetpwd)) {
      resetpwd$temp_pwd_expire[ind_pwd] <- expire
    }
    # reset counter, only when a limit is set
    if (!is.infinite(get_reset_password_max())) {
      if (!"n_user_reset" %in% colnames(resetpwd)) {
        resetpwd$n_user_reset <- rep(0, nrow(resetpwd))
      }
      n <- suppressWarnings(as.numeric(resetpwd$n_user_reset[ind_pwd]))
      resetpwd$n_user_reset[ind_pwd] <- ifelse(is.na(n), 0, n) + 1
    }

    write_db_encrypt(conn, value = users, name = "credentials", passphrase = passphrase)
    write_db_encrypt(conn, value = resetpwd, name = "pwd_mngt", passphrase = passphrase)
    invisible(TRUE)
  })
}

# SQL: row updates (nothing to re-read), optional columns only if they exist.
save_reset_pwd_sql <- function(conn, config_db, user, temp_pwd, user_info = NULL, email_col = NULL) {
  hashed_pwd <- scrypt::hashPassword(temp_pwd)
  expire <- temp_pwd_expire_value()
  udpate_users <- user

  tablename <- SQL(config_db$tables$pwd_mngt$tablename)
  request <- glue_sql(config_db$tables$pwd_mngt$select, .con = conn)
  resetpwd <- dbGetQuery(conn, request)
  # without its pwd_mngt row, the temporary password would not be temporary
  if (nrow(resetpwd) != 1) {
    stop("user not found in pwd_mngt", call. = FALSE)
  }

  values <- list(must_change = TRUE)
  if ("n_wrong_pwd" %in% colnames(resetpwd)) {
    values$n_wrong_pwd <- 0
  }
  if ("temp_pwd_expire" %in% colnames(resetpwd)) {
    values$temp_pwd_expire <- expire
  }
  if (!is.infinite(get_reset_password_max()) && "n_user_reset" %in% colnames(resetpwd)) {
    n <- suppressWarnings(as.numeric(resetpwd$n_user_reset[1]))
    values$n_user_reset <- ifelse(length(n) == 0 || is.na(n), 0, n) + 1
  }

  run_in_transaction(conn, function() {
    tablename <- SQL(config_db$tables$credentials$tablename)
    if (!is.null(user_info)) {
      request <- glue_sql(config_db$tables$credentials$select, .con = conn)
      check_reset_unchanged(dbGetQuery(conn, request), user_info, email_col)
    }
    name <- "password"
    value <- hashed_pwd
    request <- glue_sql(config_db$tables$credentials$update, .con = conn)
    dbExecute(conn, request)

    tablename <- SQL(config_db$tables$pwd_mngt$tablename)
    for (name in names(values)) {
      value <- values[[name]]
      request <- glue_sql(config_db$tables$pwd_mngt$update, .con = conn)
      dbExecute(conn, request)
    }
    invisible(TRUE)
  })
}
